### ISSUE TITLE
Help me?

### ISSUE THREAD

**Issue by ThewsyRum** [Thankgod20/Electrum-Go-Server-Flashing#1]
How can I contact you to help me resolve an issue with the execution/use of Electrum-server? Thank you in advance.

**Comment by Thankgod20** [comment]
What would you like to know. Its also worth noting that this electrum-server is for bitcoin flashing only and not for carrying out major bitcoin activities

**Comment by ThewsyRum** [comment]
No, no, it was just a small issue that I’ve already fixed, I forgot to close the issue. Now, taking the opportunity, could you compile your 'Manet' project for release? This would help people who have low-powered machines to run Android Studio, and it would also simplify and speed up the usage process. Thank you
